import dev.decision.productprice.model.ShoppingCartItem
import dev.decision.productprice.model.DiscountType

dialect "mvel"

rule "Quantity based discount"
    when
        $sci:ShoppingCartItem(quantity < 11 && quantity > 1 && product.discountType == DiscountType.QUANTITY)
    then
        $sci.setDiscount(10D);
end

rule "Quantity based discount 1"
    when
        $sci:ShoppingCartItem(quantity < 20 && quantity >= 11 && product.discountType == DiscountType.QUANTITY)
    then
        $sci.setDiscount(15D);
end

rule "Quantity based discount 2"
    when
        $sci:ShoppingCartItem(quantity >= 20 && product.discountType == DiscountType.QUANTITY)
    then
        $sci.setDiscount(25D);
end

rule "Percentage based discount"
    when
        $sci:ShoppingCartItem(quantity < 11 && quantity > 1 && product.discountType == DiscountType.PERCENTAGE)
    then
        $sci.setDiscount($sci.product.price * 0.1);
end

rule "Percentage based discount 1"
    when
        $sci:ShoppingCartItem(quantity < 20 && quantity >= 11 && product.discountType == DiscountType.PERCENTAGE)
    then
        $sci.setDiscount($sci.product.price * 0.15);
end

rule "Percentage based discount 2"
    when
        $sci:ShoppingCartItem(quantity >= 20 && product.discountType == DiscountType.PERCENTAGE)
    then
        $sci.setDiscount($sci.product.price * 0.25);
end